# Generated by Django 4.1.5 on 2023-03-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.departments'),
        ),
    ]
