# Generated by Django 4.1.5 on 2023-03-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_complete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='subject',
        ),
    ]
